# Generated by Django 3.2 on 2024-02-01 15:46

import TWC.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='The username must only contain letters and numbers.', regex='^[0-9a-zA-Z]*$')], verbose_name='Username')),
                ('id_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Number')),
                ('mobile', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('messenger_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Messenger Link')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('image', models.ImageField(blank=True, null=True, upload_to=TWC.utils.upload_image_path, verbose_name='Profile Picture')),
                ('date_activated', models.DateTimeField(blank=True, null=True, verbose_name='Date Activated')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('is_seller', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
