# Generated by Django 3.2 on 2024-02-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Mobile Number'),
        ),
    ]
