# Generated by Django 3.2 on 2024-02-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240206_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliate_code',
            field=models.CharField(blank=True, editable=False, max_length=8),
        ),
    ]
