# Generated by Django 3.2 on 2024-02-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_distributor',
            field=models.BooleanField(default=False),
        ),
    ]
