# Generated by Django 3.2 on 2024-09-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sponsor'),
        ),
    ]
