# Generated by Django 3.2 on 2024-03-19 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20240206_0854'),
        ('addresses', '0006_address_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.customer'),
        ),
    ]
