# Generated by Django 3.2 on 2024-03-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0008_auto_20240319_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='session_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
