# Generated by Django 3.2 on 2024-05-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0009_alter_address_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
