# Generated by Django 3.2 on 2024-05-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0010_alter_address_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='region_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
