# Generated by Django 3.2 on 2024-01-17 15:25

from django.db import migrations, models
import products.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('category_1', models.CharField(choices=[('promos', 'Promos'), ('sante', 'Sante Product'), ('twc', 'TWC Product'), ('chingu', 'Chingu'), ('mood', 'Mood Timepieces'), ('sante-package', 'Sante | Package')], default='sante', max_length=20, verbose_name='Category 1')),
                ('category_2', models.CharField(choices=[('sante-nutraceutical', 'Sante | Nutraceutical'), ('sante-beverage', 'Sante | Beverage'), ('sante-intimate_care', 'Sante | Intimate Care'), ('twc-freebie', 'TWC | Freebie'), ('chingu-bundle', 'Chingu | Bundle'), ('mood-bundle', 'Mood Timepieces | Bundle'), ('promo', 'Promos')], default='nutraceutical', max_length=20, verbose_name='Category 2')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Name')),
                ('description_1', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('description_2', models.TextField(blank=True, null=True, verbose_name='Long Description')),
                ('feature', models.TextField(blank=True, null=True, verbose_name='Features')),
                ('advantage', models.TextField(blank=True, null=True, verbose_name='Advantages')),
                ('benefit', models.TextField(blank=True, null=True, verbose_name='Benefits')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Specifications')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=products.utils.upload_image_path_admin, verbose_name='Image 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=products.utils.upload_image_path_admin, verbose_name='Image 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=products.utils.upload_image_path_admin, verbose_name='Image 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=products.utils.upload_image_path_admin, verbose_name='Image 4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=products.utils.upload_image_path_admin, verbose_name='Image 5')),
                ('supplier_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Supplier Price')),
                ('franchisee_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Franchisee Price')),
                ('distributor_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Member Price')),
                ('seller_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Seller Price')),
                ('customer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Customer Price')),
                ('franchisee_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Branch Markup | Franchisee Fee')),
                ('fulfiller_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Fulfiller Fee')),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Transaction Fee')),
                ('shipping_qty', models.IntegerField(default=1, verbose_name='Shipping Quantity')),
                ('barley_point', models.IntegerField(default=0, verbose_name='Barley Point')),
                ('is_for_autoship', models.BooleanField(default=False)),
                ('is_for_vw', models.BooleanField(default=False)),
                ('is_digital', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
