# Generated by Django 3.2 on 2024-03-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_1',
            field=models.CharField(choices=[('health_wellness', 'Health and Wellness'), ('healthy_beverages', 'Healthy Beverages'), ('intimate_care', 'Intimate Care'), ('bath_body', 'Bath & Body'), ('watches', 'Watches'), ('bags', 'Bags'), ('accessories', 'Accessories'), ('home_living', 'Home & Living')], default='sante', max_length=20, verbose_name='Category 1'),
        ),
    ]
