# Generated by Django 3.2 on 2023-12-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Fashion & Accessories'), (2, 'Electronics'), (3, 'Health')], null=True),
        ),
    ]
