# Generated by Django 3.2 on 2023-12-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.IntegerField(blank=True, choices=[(1, 'Apple'), (2, 'Samsung'), (3, 'Sante')], null=True),
        ),
    ]
