# Generated by Django 3.2 on 2024-06-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240606_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aggregate_rating',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3, verbose_name='Aggregate Rating'),
        ),
    ]
