# Generated by Django 3.2 on 2024-01-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240116_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Fashion & Accessories'), (2, 'Electronics'), (3, 'Health')], default=1, null=True),
        ),
    ]
