# Generated by Django 3.2 on 2024-01-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Fashion & Accessories'), (2, 'Electronics'), (3, 'Health')], null=True),
        ),
    ]
