# Generated by Django 3.2 on 2024-01-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
