# Generated by Django 3.2 on 2023-12-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_billingprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
