# Generated by Django 3.2 on 2023-12-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_delete_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
