# Generated by Django 3.2 on 2024-02-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20240206_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='referrer',
        ),
    ]
