# Generated by Django 3.2 on 2023-12-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20231218_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charge',
        ),
    ]
