# Generated by Django 3.2 on 2024-01-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingProfile',
        ),
    ]
