# Generated by Django 3.2 on 2024-02-06 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
