# Generated by Django 3.2 on 2024-02-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('prepaired', 'Prepaired'), ('shipped', 'Shipped'), ('received', 'Received')], default='processed', max_length=20),
        ),
    ]
