# Generated by Django 3.2 on 2023-12-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_customer'),
        ('orders', '0002_auto_20231219_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
