# Generated by Django 3.2 on 2024-02-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('prepared', 'Prepared'), ('shipped', 'Shipped'), ('received', 'Received')], default='processed', max_length=20),
        ),
    ]
