# Generated by Django 3.2 on 2023-12-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20231220_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=1, max_length=120),
            preserve_default=False,
        ),
    ]
