# Generated by Django 3.2 on 2023-12-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_brand'),
        ('orders', '0004_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_items',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
