# Generated by Django 3.2 on 2023-12-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_brand'),
        ('orders', '0005_order_ordered_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_items',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
