# Generated by Django 3.2 on 2024-03-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
