# Generated by Django 3.2 on 2024-03-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_quantity',
        ),
    ]
