# Generated by Django 3.2 on 2024-04-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20240331_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('bp_encoded', 'BP Encoded'), ('rts', 'RTS'), ('returned', 'Returned')], default='processed', max_length=20),
        ),
    ]
