# Generated by Django 3.2 on 2024-04-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=10, null=True),
        ),
    ]
