# Generated by Django 3.2 on 2024-04-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sponsor_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
