# Generated by Django 3.2 on 2024-04-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20240408_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sponsor-review', 'Sponsor Review'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('bp-encoded', 'BP Encoded'), ('rts', 'RTS'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
