# Generated by Django 3.2 on 2024-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20240410_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('none', 'None'), ('cod', 'Cash On Delivery')], default='none', max_length=20),
        ),
    ]
