# Generated by Django 3.2 on 2024-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fullfiller',
            field=models.CharField(choices=[('other', 'Other'), ('mandaluyong', 'Mandaluyong HUB'), ('sante valenzuela', 'Sante Valenzuela'), ('sante cdo', 'Sante CDO')], default='other', max_length=20),
        ),
    ]
