# Generated by Django 3.2 on 2024-04-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fullfiller',
            new_name='fulfiller',
        ),
    ]
