# Generated by Django 3.2 on 2024-04-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_rename_fullfiller_order_fulfiller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
