# Generated by Django 3.2 on 2024-04-15 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_cod_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=120, unique=True)),
                ('courier', models.CharField(blank=True, choices=[('j&t', 'J&T'), ('lbc', 'LBC'), ('gogoxpress', 'GogoXpress')], max_length=20, null=True)),
                ('pouch_size', models.CharField(blank=True, choices=[('sakto pack', 'Sakto Pack'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('box', 'Box'), ('others', 'Others')], max_length=20, null=True)),
                ('actual_shipping_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Pickup Date')),
                ('pade_by_fulfiller', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.courier'),
        ),
    ]
