# Generated by Django 3.2 on 2024-04-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20240415_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fulfiller',
        ),
        migrations.AddField(
            model_name='courier',
            name='booking_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='fulfiller',
            field=models.CharField(choices=[('other', 'Other'), ('mandaluyong', 'Mandaluyong HUB'), ('sante valenzuela', 'Sante Valenzuela'), ('sante cdo', 'Sante CDO')], default='other', max_length=20),
        ),
    ]
