# Generated by Django 3.2 on 2024-04-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
