# Generated by Django 3.2 on 2024-04-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_courier_tracking_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='pade_by_fulfiller',
            new_name='paid_by_fulfiller',
        ),
    ]
