# Generated by Django 3.2 on 2024-04-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_rename_pade_by_fulfiller_courier_paid_by_fulfiller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('for-booking', 'For Booking'), ('for-pickup', 'For Pickup'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('bp-encoded', 'BP Encoded'), ('vw-paid', 'VW Paid'), ('rts', 'RTS'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
