# Generated by Django 3.2 on 2024-05-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_bundle',
            field=models.BooleanField(default=False),
        ),
    ]
