# Generated by Django 3.2 on 2024-08-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_is_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fixed_shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed shipping fee value.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='is_fixed_shipping_fee',
            field=models.BooleanField(default=False, help_text='Check this to use a fixed shipping fee.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
