# Generated by Django 3.2 on 2024-08-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20240811_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fixed_shipping_fee',
        ),
    ]
