# Generated by Django 3.2 on 2024-09-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('courier', models.CharField(blank=True, choices=[('j&t', 'J&T'), ('lbc', 'LBC'), ('gogoxpress', 'GogoXpress')], max_length=20, null=True)),
                ('pouch_size', models.CharField(blank=True, choices=[('sakto pack', 'Sakto Pack'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('box', 'Box'), ('others', 'Others')], max_length=20, null=True)),
                ('actual_shipping_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Pickup Date')),
                ('fulfiller', models.CharField(choices=[('other', 'Other'), ('mandaluyong', 'Mandaluyong HUB'), ('sante valenzuela', 'Sante Valenzuela'), ('sante cdo', 'Sante CDO')], default='other', max_length=20)),
                ('paid_by_fulfiller', models.BooleanField(default=True)),
                ('booking_notes', models.TextField(blank=True)),
            ],
        ),
    ]
